### PR TITLE
Resolve simple puppet-lint notices

### PR DESCRIPTION
**Pull request by jcpunk**
A run of puppet-lint flagged these easy fixes.

### CODE REVIEW

**Comment by sanfrancrisko** [comment]
Hi @jcpunk 

It looks like there's some syntax problems [here](https://github.com/puppetlabs/puppetlabs-postgresql/pull/1191/files#diff-7f7c9a09440e6d0ba94fe8bdbfe2fbd0R34) looking at [this test failure](https://travis-ci.org/github/puppetlabs/puppetlabs-postgresql/jobs/727175146#L618)

**Comment by sanfrancrisko** [comment]
Also, just looking again, there's a number of Rubocop violations from the change too: https://travis-ci.org/github/puppetlabs/puppetlabs-postgresql/jobs/729322793#L422-L913

Autocorrect resolved a few for me (`bundle exec rake rubocop:auto_correct`), however the rest need manual intervention. If you wouldn't mind taking a look again and addressing, we'll be happy to merge 👍

**Comment by jcpunk** [comment]
In theory those bits are fixed now.

**Comment by jcpunk** [comment]
I've been looking at this a bit, and I fear I'll need some help to get it over the line....

**Comment by adrianiurca** [comment]
happy to help you @jcpunk.
Thank you for your contribution!

kind regards,
@adrianiurca

**Review by adrianiurca — APPROVED** [review]

**Pull request merged**
