### PR TITLE
Allow puppetlabs-concat 2.x

### PR DESCRIPTION
**Pull request by brandonweeks**

### CODE REVIEW

**Comment by tphoney** [comment]
@bmjen does this sound good to you ?

**Comment by bmjen** [comment]
Thanks @brandonweeks. The .fixtures.yml file also needs to be updated.

**Comment by brandonweeks** [comment]
@bmjen do you want it pinned to 2.1.0? I left it alone since it wasn't pinned to any version at the moment.

**Comment by bmjen** [comment]
@brandonweeks I think unpinning it entirely and having it use master should be fine.

**Comment by brandonweeks** [comment]
@bmjen concat was already unpinned here.

**Comment by bmjen** [comment]
Cool. Thanks @brandonweeks !

**Pull request merged**
