### PR TITLE
add default version for Fedora 35

### PR DESCRIPTION
**Pull request by jflorian**
Signed-off-by: John Florian <jflorian@doubledog.org>

### CODE REVIEW

**Review by ekohl — APPROVED** [review]

**Comment by lweller** [comment]
Would it be possible to merge this PR soon as Fedora 35 was released some months ago now.

**Review by smortex — APPROVED** [review]

**Comment by ekohl** [comment]
I completely forgot about this. After approving I started CI and forgot to check back.

**Comment by lweller** [comment]
@ekohl thank you for your fast reaction to my comment. Would it be possible to build a new release soon, so that we can reference an official version instead of a specific commit.

**Comment by ekohl** [comment]
I started https://github.com/puppetlabs/puppetlabs-postgresql/runs/4951722999?check_suite_focus=true but it's been running for over an hour. That's not normal.

**Comment by ekohl** [comment]
It finally opened https://github.com/puppetlabs/puppetlabs-postgresql/pull/1320.

**Pull request merged**
