### PR TITLE
add ubuntu/vivid support

### PR DESCRIPTION
**Pull request by saimonn**
trivial commit to add support for ubuntu 15.04 "vivid"

### CODE REVIEW

**Comment by ckaenzig** [comment]
:+1: boring but necessary :)

**Comment by gcmalloc** [comment]
:+1:

**Comment by nibalizer** [comment]
:+1:

**Comment by oysteing** [comment]
Vivid has swapped to systemd as the default init system. Shouldn't the service status detection be updated to, just like for Debian Jessie? https://github.com/puppetlabs/puppetlabs-postgresql/pull/586

**Comment by nibalizer** [comment]
@oysteing is quite correct. Sad that the RAL fails here.

**Comment by raphink** [comment]
Can this be merged please?

**Pull request merged**
