### PR TITLE
Postgresql 9.4 uses Postgis 2.1

### PR DESCRIPTION
**Pull request by raphink**

### CODE REVIEW

**Comment by igalic** [comment]
:+1:

**Comment by raphink** [comment]
Thanks for pinging @igalic

**Comment by saimonn** [comment]
I would also need this PR. Please @mhaskel / @cmurphy  ?

**Comment by saimonn** [comment]
https://github.com/puppetlabs/puppetlabs-postgresql/commit/9bb1c5e491463fe64beff663be156d6724b4e06e fixes this PR.

**Pull request closed without merging**
