### PR TITLE
Ensure the confdir exists.

### PR DESCRIPTION
**Pull request by ddryden**
It's passing the unit tests.

### CODE REVIEW

**Comment by ddryden** [comment]
Maybe Travis was having a bad day can I trigger another test?

> An error occurred while loading ./spec/acceptance/00-utf8_encoding_spec.rb.
> Failure/Error: require 'beaker-rspec/spec_helper'
> Docker::Error::TimeoutError:
>   read timeout reached

I just made a PR on my fork and ran it with Travis and I don't get the same error: [here](https://travis-ci.org/ddryden/puppetlabs-postgresql/builds/352309933)

**Comment by smortex** [comment]
@ddryden you can trigger a new build by closing and re-opening a ticket, but this makes borring notifications.  I personally prefer to amend my last commit and force push of the unchanged code.  Since the commit is different, a new build is triggered:

```
git commit --amend
git push -f
```

**Comment by pmcmaw** [comment]
Hey @ddryden 
Great PR, just wondering if you could get some tests and docs added and I will get this PR merged. 👍

**Comment by david22swan** [comment]
@ddryden Apologies but due to the length of time this PR has been left to lie fallow and your lack of response to a the above message I feel that I must know close this PR.
I'm sorry if this inconveniences you in any way and we will of course be more than happy to review it again in the future if you decide to reopen it. 
Best Wishes

**Pull request closed without merging**
