### PR TITLE
pdksync - (IAC-1709) - Add Support for Debian 11

### PR DESCRIPTION
**Pull request by david22swan**
(IAC-1709) - Add Support for Debian 11
pdk version: `2.1.1`

### CODE REVIEW

**Comment by david22swan** [comment]
Spec test failures are unrelated and are showing on main.
Centos-8 failures originate from the setup and are known.

**Review by smortex — APPROVED** [review]
LGTM

**Comment by ekohl** [comment]
I'll first merge https://github.com/puppetlabs/puppetlabs-postgresql/pull/1289 and see what fails after that.

**Comment by ekohl** [comment]
Rebased on top of https://github.com/puppetlabs/puppetlabs-postgresql/pull/1291 now that the tests should be green again.

**Review by ekohl — APPROVED** [review]

**Review by bastelfreak — APPROVED** [review]

**Comment by ekohl** [comment]
Looks like the CLA check is not responding and I can't merge without that, even though it was previously green and I'm sure @david22swan has signed it. I'm quite eager to get this merged.

**Pull request merged**
