### PR TITLE
Fixing autodetected version for Debian Jessie, which should use postgresql 9.4

### PR DESCRIPTION
**Pull request by Zouuup**

### CODE REVIEW

**Comment by mmoll** [comment]
BTW, this would solve MODULES-1603

**Comment by mfn** [comment]
Are there plans for a new release? Would be great to have 9.4 support in the module available.

**Comment by igalic** [comment]
@mfn: you could propose a release yourself, like so: https://github.com/puppetlabs/puppetlabs-postgresql/pull/478

**Comment by mfn** [comment]
Wouldn't [pg_hba_rule.php](https://github.com/puppetlabs/puppetlabs-postgresql/blob/b0f2a8f765f4bf05950e15700dfaff93f569936c/manifests/server/pg_hba_rule.pp#L28) also need an entry for 9.4?

**Comment by igalic** [comment]
@mfn looking at this code, it should work with the default, aaand, we should fix it so it works better.
There's way too much repetition, and, i have no idea what, exactly, that default is supposed to be.

**Pull request merged**
