### PR TITLE
Allow working directory to be configurable via globals (instead of always using /tmp)

### PR DESCRIPTION
**Pull request by hdeadman**
When running on a server with /tmp mounted with "noexec" option in fstab (to satisfy security) I was getting an error like: 

Error: Error executing SQL; psql returned 256: 'could not change directory to "/root"

which was resolved for most people back in version 2.2.1 by setting /tmp as the working directory for psql. I need to set the folder to something else now that /tmp is secure so this pull request makes /tmp configurable. 

This pull also has a commit from another pull request I have open that is waiting for 4.6.1 to come out so the tests will pass.

### CODE REVIEW

**Comment by hdeadman** [comment]
Opened ticket [MODULES-3759](https://tickets.puppetlabs.com/browse/MODULES-3759)

**Comment by eputnam** [comment]
thanks for the PR! please add the new param to the readme and add some tests.

**Comment by hdeadman** [comment]
I updated the documentation and added a couple tests. Let me know if you want tests that cover every class or define where the the attribute is used.

**Comment by eputnam** [comment]
merging. out of curiosity, is there a reason psql needs to be run in a particular dir? does the dir need to be writable?

**Comment by hdeadman** [comment]
@eputnam - I was having problems on a server with /tmp mounted in /etc/fstab with noexec option. There is a security check in the [scap security guide](https://github.com/OpenSCAP/scap-security-guide/blob/8cd9fb09b1fbde47c7376bdf117452d427db787c/RHEL/7/input/xccdf/system/permissions/partitions.xml#L111) that calls for that. I don't recall exactly which part of module was breaking but when I google'd error message it brought me to the release notes for the change that made psql use /tmp to begin with.

**Pull request merged**
