### PR TITLE
Drop postgresql 8.1/RHEL5 specific code

### PR DESCRIPTION
**Pull request by bastelfreak**
## Summary
Provide a detailed description of all the changes present in this pull request.

## Additional Context
Add any additional context about the problem here. 
- [ ] Root cause and the steps to reproduce. (If applicable)
- [ ] Thought process behind the implementation.

## Related Issues (if any)
Mention any related issues or pull requests.

## Checklist
- [ ] 🟢 Spec tests.
- [ ] 🟢 Acceptance tests.
- [ ] Manually verified. (For example `puppet apply`)

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
If you do this, I'd also drop setting the default to 8.1 for some OSes and also remove test code.

And dropping 8.1 is probably fine, but I think Puppetlabs will want to continue supporting RHEL 6 while that's supported by Red Hat and that means keeping 8.4 I think.

**Comment by bastelfreak** [comment]
I dropped all postgresql 8.1 or RHEL 5 specific code. The metadata.json only mentions RHEL7 and newer so I think that's fine.

**Review by Ramesh7 — APPROVED** [review]

**Comment by ekohl** [comment]
> The metadata.json only mentions RHEL7 and newer so I think that's fine.

In the past Puppet has had this weird policy where they didn't list something in `metadata.json` but then did support it, sort of. I don't like it, because it makes life harder but since it's in their namespace I have tried to respect it.

**Comment by alexjfisher** [comment]
@bastelfreak Following this change, I don't think https://github.com/puppetlabs/puppetlabs-postgresql/blob/04a3fbe6358b1f897444cb520e488ebdaff5cbaf/manifests/server/database.pp#L35 does anything?

**Pull request merged**
