### PR TITLE
MODULES-9138 - release_prep v 6.0.1

### PR DESCRIPTION
**Pull request by lionce**

### CODE REVIEW

**Comment by lionce** [comment]
Apparently there are no changes. I'm closing this PR

**Comment by alexjfisher** [comment]
> Apparently there are no changes. I'm closing this PR

This release is needed for https://github.com/puppetlabs/puppetlabs-postgresql/pull/1079

**Comment by MikaelSmith** [comment]
How are release notes handled for this project? I see a CHANGELOG, we should update it.

**Comment by pmcmaw** [comment]
This is an old release. I am closing this PR. 
I am working on a release now and should have new release prep up as soon as I can.

**Pull request closed without merging**
