### PR TITLE
Support granting permission on sequences.

### PR DESCRIPTION
**Pull request by qha**
This pull request adds support for granting permission on sequences.

### CODE REVIEW

**Comment by qha** [comment]
Also puppetlabs ticket MODULES-2139:
https://tickets.puppetlabs.com/browse/MODULES-2139

**Comment by jonnytpuppet** [comment]
Hi There

Thanks for this PR. I'd love to see it merged. It would be great if you could add a test case for this, as well as update the README file. Once this is done, we'll be sure to merge ASAP.

Thanks!

**Comment by qha** [comment]
There, the build bot is still happy, i hope this will do.

**Comment by igalic** [comment]
hey @qha. this looks really good!

can you please squash the last two commits together?

(also, you might wanna change your commit authors to be the same, or add the email address to your github profile for extra magick internet points)

**Comment by qha** [comment]
Apparently i can and i take it the build bot will still be happy as only the history has changed...

**Pull request closed without merging**
