### PR TITLE
Ignore .psqlrc so command output is clean and don't break Puppet

### PR DESCRIPTION
**Pull request by flaviogurgel**

### CODE REVIEW

**Comment by flaviogurgel** [comment]
I can't see why Travis tests fail. The same tests manually work for me, it seems to be not related to the changes I'm proposing.

**Comment by kinncj** [comment]
You need to check all builds on travis... The failing ones are explicitly telling what are the possible errors.
Example https://travis-ci.org/puppetlabs/puppetlabs-postgresql/jobs/368627301#L1301

**Comment by flaviogurgel** [comment]
I've already done that @kinncj what I wanted to say is that the same tests indicated by Travis (actually the three tests that fail and do that in the same way) are passing on my local system, so I have some hard time trying to figure out what's going on.

**Comment by fcantournet** [comment]
there seems to be an explicit test for flags provided to postgresl here :
spec/unit/puppet/provider/postgresql_psql/ruby_spec.rb 

We need to add -X to the list in a couple of places in this file

**Comment by flaviogurgel** [comment]
@fcantournet done, thanks. I'm looking for the other errors now.

**Comment by flaviogurgel** [comment]
Now that one last test is red, I've installed a full 2.1.9 ruby env in my machine and the error appears.
I've commented the code that generates the warning : 
Support for ruby version 2.1.9 is deprecated and will be removed in a future release. See https://docs.puppet.com/puppet/latest/system_requirements.html#ruby for a list of supported ruby versions.

And the test runs 'till the end without problems.

**Comment by flaviogurgel** [comment]
The latest test seems to be fixed upstream, all green now.

**Comment by pmcmaw** [comment]
Closing and reopening to trigger Travis with new test configuration.

**Comment by pmcmaw** [comment]
@david22swan are you able to confirm that this passed adhoc so we can get it merged, the link does not provide any visibility to whether this PR is ready for merge.

**Comment by david22swan** [comment]
@flaviogurgel @pmcmaw 
The adhoc run failed when I ran it.

**Comment by flaviogurgel** [comment]
Now that the checks are green (other stuff have been surely repaired), is it necessary to have adhoc runs to merge it? If yes, how can I help launching one?
I have this code in my production (over 60 database servers) without glitches since I opened this PR. This bug impacts other users as we can see https://tickets.puppetlabs.com/browse/MODULES-5374

**Comment by david22swan** [comment]
@flaviogurgel If it is not to much trouble would you mind rebasing your changes onto the master. The adhoc failures look like something we fixed at an earlier point.

**Comment by flaviogurgel** [comment]
Thanks @david22swan I have just rebased my local branch onto the master and nothing has changed since my last push, it should be good to merge.

**Comment by david22swan** [comment]
This is still failing when run against adhoc.

```
01:15:50 An error occurred while loading ./spec/acceptance/alternative_port_spec.rb.
01:15:50 Failure/Error: require 'beaker/task_helper'
01:15:50 LoadError:
01:15:50   cannot load such file -- beaker/task_helper
01:15:50   
01:15:50 # ./spec/spec_helper_acceptance.rb:6:in `require'
01:15:50 # ./spec/spec_helper_acceptance.rb:6:in `<top (required)>'
01:15:50 # ./spec/acceptance/alternative_port_spec.rb:1:in `require'
01:15:50 # ./spec/acceptance/alternative_port_spec.rb:1:in `<top (required)
```

**Comment by david22swan** [comment]
Pretty sure it need's another rebase. Apologies for the wait

**Comment by flaviogurgel** [comment]
@david22swan what is meant to be rebased?
I've just checked out, the master branch didn't change since my last push, there's nothing to rebase on. Maybe I'm wrong, I didn't get the point anyway.

**Comment by david22swan** [comment]
@flaviogurgel Are you sure? Because github is showing your branch as being 72 commits behind the puppetlabs master.
And the reason is due to there being various changes to how beaker is run since your pr was first created which mean that we are unable to run your changes against the adhoc test pipeline successfully.

**Comment by david22swan** [comment]
Are you checking that master branch of your personal fork? Or the branch of the actual puppetlabs master?

**Comment by flaviogurgel** [comment]
Please see my new PR for this subject https://github.com/puppetlabs/puppetlabs-postgresql/pull/1021

**Pull request closed without merging**
