### PR TITLE
maint: removing debian 12 from metadata

### PR DESCRIPTION
**Pull request by malikparvez**
Partially reverts puppetlabs/puppetlabs-postgresql#1460

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
Can we do a partial revert and only remove it from metadata.json?

**Comment by bastelfreak** [comment]
why does it need to be reverted? It works fine on Debian 12.

**Comment by malikparvez** [comment]
@ekohl yes that might work, thanks for the suggestion

**Comment by ekohl** [comment]
I think it's fair if it isn't tested in acceptance tests (which right now it isn't).

**Review by jordanbreen28 — APPROVED** [review]

**Pull request merged**
