### PR TITLE
Allow username and password as integers

### PR DESCRIPTION
**Pull request by sathieu**
Fixes: String can't be coerced into Fixnum

### CODE REVIEW

**Comment by sathieu** [comment]
See https://github.com/2ndquadrant-it/puppet-barman/pull/29#issuecomment-227210810

**Comment by bmjen** [comment]
Thanks for the contribution @sathieu! Can you fix the acceptance tests failures? It appears that the service is not listening on the port after the change.

**Comment by sathieu** [comment]
The test fail for another reason:
```
Gem::InstallError: mime-types-data requires Ruby version >= 2.0.
```
Nothing to do with my PR.

**Comment by bmjen** [comment]
@sathieu I believe that error was fixed in master by pinning json_pure if ruby < 2.0. Can you rebase from master and push again? Sorry!

**Comment by sathieu** [comment]
@bmjen. Done. CI in progress.

**Comment by bmjen** [comment]
Thanks @sathieu . The unit test failures on puppet 4 are a known issue.

**Pull request merged**
