### PR TITLE
Write facts as shared examples, move to Debian 11 and follow rspec-puppet path conventions

### PR DESCRIPTION
**Pull request by ekohl**
rspec-puppet places all classes in spec/classes and automatically applies the correct type. The same is true for defines in spec/defines.

Previously there was a lot of duplication between facts. This now stores them as shared examples in `spec_helper_local.rb` and also extracts them from rspec-puppet-facts where possible.

Debian 8 isn't in metadata.json anymore which meant it was testing for an unsupported OS by default. It's now changed to Debian 11.

### CODE REVIEW

**Review by bastelfreak — APPROVED** [review]

**Comment by daianamezdrea** [comment]
Hi @ekohl, can you rebase your PR please ? Thank you !

**Comment by ekohl** [comment]
Rebased

**Review by bastelfreak — APPROVED** [review]
looks good to me. happy to merge if tests pass

**Comment by ekohl** [comment]
Looks like lint failed, but I wonder why it didn't fail before since I'm not changing that.

**Comment by ekohl** [comment]
Marking it as draft since I'm abusing CI to see if my code passes because of https://tickets.puppetlabs.com/browse/MODULES-11161. If the tests are green, it should be ready.

**Comment by ekohl** [comment]
This is now failing on https://github.com/puppetlabs/puppetlabs-postgresql/pull/1313#discussion_r798456019. I'm hoping @fe80 can shed some light on this.

**Review by bastelfreak — APPROVED** [review]
looks good to me. the tests fail also on main, so I think merging it is fine.

**Pull request merged**
