### PR TITLE
drop code for Debian 6/7 and Ubuntu 10.04/12.04

### PR DESCRIPTION
**Pull request by evgeni**
Support for these was dropped in 3d1e1e31 and e61579ff, but the code
remained.

### CODE REVIEW

**Review by smortex — DISMISSED** [review]
Make sense!

**Comment by evgeni** [comment]
The test failures look unrelated to this change.

**Comment by ekohl** [comment]
Test failures should be fixed with https://github.com/puppetlabs/puppetlabs-postgresql/commit/09b242a9307a3948f3530c5e8402e8827e5502d0. Mind rebasing.

**Comment by evgeni** [comment]
rebased

**Comment by ekohl** [comment]
Test failures are relevant. Sadly the tests in this module are quite dated.

**Comment by evgeni** [comment]
Updated the tests from D6 to D10 (there is no D11 for reasons ;))

**Comment by ekohl** [comment]
https://github.com/puppetlabs/puppetlabs-postgresql/pull/1288 should add D11, but there's some CI issue.

**Review by ekohl — APPROVED** [review]
Thanks!

**Comment by david22swan** [comment]
@evgeni @ekohl 
Change's look good to me and since the test failures are a known issue gonna go ahead and merge.
Setting the change to bugfix as support for the OS's has already been removed.

**Comment by ekohl** [comment]
@david22swan any idea why CentOS 8 is failing? I can only see that it's timing out but is there a log of the actual run?

**Pull request merged**
