### PR TITLE
Do not restart service for timezone change

### PR DESCRIPTION
**Pull request by DavidS**
See https://github.com/puppetlabs/puppetlabs-postgresql/commit/81706ea9fca8c859a06a41a4eaf5ebb5a88ce8c7#commitcomment-19978717

### CODE REVIEW

**Comment by hasegeli** [comment]
I think there is something broken somewhere in *reloading* the configuration.  That is why people submit pull request to add unnecessary items to this list.  See also #791.

**Comment by DavidS** [comment]
@hasegeli I'm thankful for any hint.

**Comment by DavidS** [comment]
I've also created https://tickets.puppetlabs.com/browse/MODULES-4144 to track this.

**Comment by eputnam** [comment]
sorry, @hasegeli was in line before you on config_entry.pp...

**Comment by hasegeli** [comment]
I incorporated this into #868.

**Comment by eputnam** [comment]
closing in favor of #868

**Pull request closed without merging**
