### PR TITLE
[IAC-1735] Fix test suite

### PR DESCRIPTION
**Pull request by ekohl**
Continuation of https://github.com/puppetlabs/puppetlabs-postgresql/pull/1289. Individual commits have more details.
Closes: #1289

### CODE REVIEW

**Comment by smortex** [comment]
We needs one more `let(:postgresql_version) { '9.6' }` to replace the condition that trigger the error.

**Comment by ekohl** [comment]
I wish PDK actually worked on Ruby 3 so I could run things locally.

**Review by bastelfreak — APPROVED** [review]

**Review by smortex — APPROVED** [review]

**Review by alexjfisher — APPROVED** [review]

**Comment by ekohl** [comment]
Looks like CentOS 8 timed out but this doesn't really touch acceptance tests so shall we merge this? I'm hesitant to merge my own PRs.

**Comment by bastelfreak** [comment]
merging this since it only fixes the CI pipeline and unblocks other PRs.

**Pull request merged**
