### PR TITLE
Fix line endings

### PR DESCRIPTION
**Pull request by karyon**
See https://github.com/puppetlabs/puppetlabs-concat/pull/80 for an explanation.

i had no issues with the .rb file, but added it as well because i guessed all shebang lines are probably broken with windows line endings.

it should also be possible to just add the files with shebang lines to the gitattributes file instead of those very inclusive filters, if you prefer that.

### CODE REVIEW

**Comment by igalic** [comment]
this is something i'd rather see in [modulesync_configs](https://github.com/puppetlabs/modulesync_configs/)

**Comment by karyon** [comment]
actually, i have a similar PR open in concat: https://github.com/puppetlabs/puppetlabs-concat/pull/373, so... yeah.

should i open a PR there with exactly the same changes?

**Comment by igalic** [comment]
yes, please.

**Comment by bmjen** [comment]
Going to close this in lieu of doing with this modulesync PR.

https://github.com/puppetlabs/modulesync_configs/pull/39

**Comment by bmjen** [comment]
Changed my mind. Probably don't want to wait for us to modulesync this.

**Pull request merged**
