### PR TITLE
port: Enforce Stdlib::Port datatype

### PR DESCRIPTION
**Pull request by bastelfreak**
## Summary
Provide a detailed description of all the changes present in this pull request.

## Additional Context
Add any additional context about the problem here. 
- [ ] Root cause and the steps to reproduce. (If applicable)
- [ ] Thought process behind the implementation.

## Related Issues (if any)
Mention any related issues or pull requests.

## Checklist
- [ ] 🟢 Spec tests.
- [ ] 🟢 Acceptance tests.
- [ ] Manually verified. (For example `puppet apply`)

### CODE REVIEW

**Review by SimonHoenscheid — DISMISSED** [review]

**Comment by ekohl** [comment]
I don't mind this, but can we wait until there are more backwards incompatible changes lined up? Perhaps even implement a deprecation where it changes the tests to integers and generates a warning in the stable release that string ports will be removed in the next release?

**Comment by bastelfreak** [comment]
@ekohl we will soonish merge #1450 and that will be a major release. I wanted to change the port within that major release.

**Comment by bastelfreak** [comment]
I will see if we can do a minor release before merging #1450 , then we could release a warning

**Comment by bastelfreak** [comment]
let's merge and release https://github.com/puppetlabs/puppetlabs-postgresql/pull/1474 before #1473

**Comment by bastelfreak** [comment]
This should be merged after the 9.2.0 release

**Comment by bastelfreak** [comment]
This is now ready for review and merge

**Review by SimonHoenscheid — APPROVED** [review]
LGTM

**Review by SimonHoenscheid — APPROVED** [review]

**Review by smortex — APPROVED** [review]

**Review by jcpunk — APPROVED** [review]

**Review by ekohl — APPROVED** [review]

**Pull request merged**
