### PR TITLE
Remove extra blanks and backslashes.

### PR DESCRIPTION
**Pull request by smortex**

### CODE REVIEW

**Comment by DavidS** [comment]
@jbondpdx can you take a look at this?

**Comment by jbondpdx** [comment]
This looks fine to me, @DavidS: the slashes are unnecessary in Github and the Forge. That said, @jtappa has been working on a major refactor of this doc, so I'd like her to look at it before merge. I don't want to create conflicts with what she's got.

**Comment by jtappa** [comment]
@jeanbondpdx, @davidS My merge will be hairy in any case, I say go for it, and I'll deal with it when my overhaul gets submitted. :+1:

**Comment by DavidS** [comment]
Thanks everyone!

**Pull request merged**
